package resourcetype

// ZIA Resource names, defined in place, used throughout the provider and tests
const (
	URLCategories                   = "zia_url_categories"
	URLFilteringRules               = "zia_url_filtering_rules"
	FirewallFilteringRules          = "zia_firewall_filtering_rule"
	FirewallIPSRules                = "zia_firewall_ips_rule"
	FirewallDNSRules                = "zia_firewall_dns_rule"
	FileTypeControlRules            = "zia_file_type_control_rules"
	FWFilteringDestinationGroup     = "zia_firewall_filtering_destination_groups"
	FWFilteringSourceGroup          = "zia_firewall_filtering_ip_source_groups"
	FWFilteringNetworkServices      = "zia_firewall_filtering_network_service"
	FWFilteringNetworkServiceGroups = "zia_firewall_filtering_network_service_groups"
	FWFilteringNetworkAppGroups     = "zia_firewall_filtering_network_application_groups"
	ForwardingControlRule           = "zia_forwarding_control_rule"
	ForwardingControlZPAGateway     = "zia_forwarding_control_zpa_gateway"
	TrafficForwardingStaticIP       = "zia_traffic_forwarding_static_ip"
	TrafficForwardingGRETunnel      = "zia_traffic_forwarding_gre_tunnel"
	TrafficForwardingVPNCredentials = "zia_traffic_forwarding_vpn_credentials"
	TrafficForwardingLocManagement  = "zia_location_management"
	LocationGroups                  = "zia_location_groups"
	CloudAppControlRule             = "zia_cloud_app_control_rule"
	DLPDictionaries                 = "zia_dlp_dictionaries"
	DLPEngines                      = "zia_dlp_engines"
	DLPNotificationTemplates        = "zia_dlp_notification_templates"
	DLPWebRules                     = "zia_dlp_web_rules"
	AdminUsers                      = "zia_admin_users"
	Users                           = "zia_user_management"
	RuleLabels                      = "zia_rule_labels"
	SandboxRules                    = "zia_sandbox_rules"
	SSLInspectionRules              = "zia_ssl_inspection_rules"
	AuthSettingsURLs                = "zia_auth_settings_urls"
	Activation                      = "zia_activation_status"
	AdminRoles                      = "zia_admin_roles"
	SubscriptionAlerts              = "zia_subscription_alert"
	ForwardingControlProxies        = "zia_forwarding_control_proxies"
	NatControlRules                 = "zia_nat_control_rules"
	ServiceEdgeCluster              = "zia_virtual_service_edge_cluster"
	NSSServer                       = "zia_nss_server"
)
