#!/bin/bash

# SetEnv takes two arguments, key and value
SetEnv () {
  echo "$1=$2"
  export $1="$2"
}

SetEnv SKIP_ADMIN_USERS "no"
SetEnv SKIP_ADMIN_USERS "no"
SetEnv SKIP_DLP_DICTIONARIES "no"
SetEnv SKIP_DLP_WEB_RULES "no"
SetEnv SKIP_FIREWALL_FILTERING_RULE "no"
SetEnv SKIP_FIREWALL_FILTERING_RULE "no"
SetEnv SKIP_FW_IP_DESTINATION_GROUPS "no"
SetEnv SKIP_FW_IP_SOURCE_GROUPS "no"
SetEnv SKIP_FW_NETWORK_APPLICATION_GROUPS "no"
SetEnv SKIP_FW_NETWORK_SERVICE_GROUPS "no"
SetEnv SKIP_FW_NETWORK_SERVICES "no"
SetEnv SKIP_LOCATION_MANAGEMENT "no"
SetEnv SKIP_RULE_LABELS "no"
SetEnv SKIP_TRAFFIC_FORWARDING_GRE_TUNNEL "no"
SetEnv SKIP_TRAFFIC_FORWARDING_STATIC_IP "no"
SetEnv SKIP_TRAFFIC_FORWARDING_VPN_CREDENTIALS "no"
SetEnv SKIP_URL_CATEGORIES "no"
SetEnv SKIP_URL_FILTERING_RULES "no"
