name: Acceptance Test Schedule

# Runs acceptance tests on a cron schedule

on:
  schedule:
    - cron: 0 14 * * MON-FRI # Every weekday at 14:00 UTC (10a Eastern)

concurrency: acceptance_tests

jobs:
  acceptance:
    runs-on: ubuntu-latest

    steps:
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17.x

      - name: Checkout
        uses: actions/checkout@v2

      - name: make testacc
        run: make testacc
        env:
          TESTARGS: -parallel 20
          ZIA_USERNAME: ${{ secrets.ZIA_USERNAME }}
          ZIA_PASSWORD: ${{ secrets.ZIA_PASSWORD }}
          ZIA_API_KEY: ${{ secrets.ZIA_API_KEY }}
          ZIA_BASE_URL: ${{ secrets.ZIA_BASE_URL }}
