# This GitHub action runs your tests for each commit push and/or PR. Optionally
# you can turn it on using a cron schedule for regular testing.
#
name: CI
on:
  push:
    branches: [ master ]
    paths-ignore:
      - 'README.md'
      - 'docs/**'
      - 'cli/**'

  pull_request:
    branches: [ master ]
    paths-ignore:
      - 'README.md'
      - 'docs/**'
      - 'cli/**'
  # For systems with an upstream API that could drift unexpectedly (like most SaaS systems, etc.),
  # we recommend testing at a regular interval not necessarily tied to code changes. This will
  # ensure you are alerted to something breaking due to an API change, even if the code did not
  # change.

  schedule:
    - cron: '0 13 * * *'

jobs:
  # ensure the code builds...
  build:
    name: Build
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.18'
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v3

    - name: Download Go Dependencies
      run: |
        go mod vendor && go mod tidy

    - name: Setup Go Tools
      run: make tools

    - name: Check Formatting
      run: make fmtcheck

    - name: Build
      run: |
        go build -v .

    - name: Vet Code
      run: make vet

  golangci:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v4
        with:
          go-version: 1.18
      - uses: actions/checkout@v3
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: latest
          args: --timeout=60m
          only-new-issues: true

  # run acceptance tests
  test:
    needs: build
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: ^1.18
      id: go

    - uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: '>=0.13.x'
        terraform_wrapper: false

    - name: Check out code into the Go module directory
      uses: actions/checkout@v3

    - name: Download Go Dependencies
      run: |
        go mod vendor && go mod tidy

    - name: TF acceptance tests
      env:
        TF_ACC: true
        ZIA_USERNAME: ${{ secrets.ZIA_USERNAME }}
        ZIA_PASSWORD: ${{ secrets.ZIA_PASSWORD }}
        ZIA_API_KEY: ${{ secrets.ZIA_API_KEY }}
        ZIA_CLOUD: ${{ secrets.ZIA_CLOUD }}
        TF_CLI_ARGS_apply: -parallelism=1

        # Set whatever additional acceptance test env vars here. You can
        # optionally use data from your repository secrets using the
        # following syntax:
        # SOME_VAR: ${{ secrets.SOME_VAR }}
      run: |
        go test -v -cover ./zia -v -parallel 30  -timeout 60m
        go mod vendor && go mod tidy
        go build ./cli/ziaActivator.go
        mv ziaActivator /usr/local/bin
        ziaActivator

