on:
  workflow_call:
    inputs:
      environment:
        description: The GitHub environment to use
        type: string
        required: true
    secrets:
      ZIA_USERNAME:
        required: true
      ZIA_PASSWORD:
        required: true
      ZIA_API_KEY:
        required: true
      ZIA_CLOUD:
        required: true
      ZIA_ACC_TEST_FORCE_SWEEPERS:
        required: true
      TF_ACC:
        required: true

jobs:
  zia-test:
    environment: ${{ inputs.environment }}
    strategy:
      matrix:
        go-version: [1.20]
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.20"

      - name: Setup Go Tools
        run: make tools

      - name: Download Go Dependencies
        run: |
          go mod tidy && go mod vendor

      - name: Setup Go Tools
        run: make tools

      - name: Check Formatting
        run: make fmtcheck

      - name: Vet Code
        run: make vet

      - name: Lint Code
        run: make lint

      - name: Check Build
        run: make build
      - name: Run tests with retry
        uses: nick-invision/retry@v2
        with:
          max_attempts: 3
          timeout_minutes: 120
          command: |
            make sweep
            go test -v -cover ./zia -v -parallel 30 -timeout 120m
            go mod vendor && go mod tidy
            go build ./cli/ziaActivator.go
            mv ziaActivator /usr/local/bin
            make sweep
            ziaActivator
        env:
          ZIA_USERNAME: ${{ secrets.ZIA_USERNAME }}
          ZIA_PASSWORD: ${{ secrets.ZIA_PASSWORD }}
          ZIA_API_KEY: ${{ secrets.ZIA_API_KEY }}
          ZIA_CLOUD: ${{ secrets.ZIA_CLOUD }}
          ZIA_ACC_TEST_FORCE_SWEEPERS: ${{ secrets.ZIA_ACC_TEST_FORCE_SWEEPERS }}
          TF_ACC: ${{ secrets.TF_ACC }}
