name: ZIA Test
on:
  pull_request:
    types: [opened, synchronize]
  merge_group:
    types: [checks_requested]
  push:
    branches:
      - master

  # For systems with an upstream API that could drift unexpectedly (like most SaaS systems, etc.),
  # we recommend testing at a regular interval not necessarily tied to code changes. This will
  # ensure you are alerted to something breaking due to an API change, even if the code did not
  # change.

  schedule:
    - cron: '0 13 * * 1-5' # UTC
  workflow_dispatch:

jobs:
  zia-zsbeta-tests:
    environment: ZIA_ZSBETA
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        goVersion: ["1.21"]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.goVersion }}

      - name: Set Go env
        run: |
          echo "GOPATH=$(go env GOPATH)" >> $GITHUB_ENV
          echo "$(go env GOPATH)/bin" >> $GITHUB_PATH

      - name: Setup Go Tools
        run: make tools

      - name: Download Go Dependencies
        run: |
          go mod tidy && go mod vendor

      - name: Setup Go Tools
        run: make tools

      - name: Check Formatting
        run: make fmtcheck

      - name: Vet Code
        run: make vet

      - name: Lint Code
        run: make lint

      - name: Check Build
        run: make build

      - name: Run tests with retry
        uses: nick-fields/retry@v3
        with:
          max_attempts: 3
          timeout_minutes: 45
          command: |
            make sweep
            go test -v -cover ./zia -v -parallel 10 -timeout 60m
            make sweep

        env:
          ZIA_USERNAME: ${{ secrets.ZIA_USERNAME }}
          ZIA_PASSWORD: ${{ secrets.ZIA_PASSWORD }}
          ZIA_API_KEY: ${{ secrets.ZIA_API_KEY }}
          ZIA_CLOUD: ${{ secrets.ZIA_CLOUD }}
          ZIA_SANDBOX_TOKEN: ${{ secrets.ZIA_SANDBOX_TOKEN }}
          ZPA_CLIENT_ID: ${{ secrets.ZPA_CLIENT_ID }}
          ZPA_CLIENT_SECRET: ${{ secrets.ZPA_CLIENT_SECRET }}
          ZPA_CUSTOMER_ID: ${{ secrets.ZPA_CUSTOMER_ID }}
          ZPA_CLOUD: ${{ secrets.ZPA_CLOUD }}
          TF_ACC: ${{ secrets.TF_ACC }}
          ZIA_ACC_TEST_FORCE_SWEEPERS: ${{ secrets.ZIA_ACC_TEST_FORCE_SWEEPERS }}

  zia-test-tenants:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        goVersion: ["1.21"]
        environment:
          - ZIA_ZSCLOUD
          - ZIA_ZS0
          - ZIA_ZS3
    environment: ${{ matrix.environment }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.goVersion }}

      - name: Set Go env
        run: |
          echo "GOPATH=$(go env GOPATH)" >> $GITHUB_ENV
          echo "$(go env GOPATH)/bin" >> $GITHUB_PATH

      - name: Setup Go Tools
        run: make tools

      - name: Download Go Dependencies
        run: |
          go mod tidy && go mod vendor

      - name: Setup Go Tools
        run: make tools

      - name: Check Formatting
        run: make fmtcheck

      - name: Vet Code
        run: make vet

      - name: Lint Code
        run: make lint

      - name: Check Build
        run: make build

      - name: Run tests with retry on Ubuntu
        uses: nick-fields/retry@v3
        with:
          max_attempts: 3
          timeout_minutes: 45 # Adjust as needed
          command: |
            make sweep
            go test -v -cover ./zia -v -parallel 10 -timeout 60m
            make sweep
        env:
          ZIA_USERNAME: ${{ secrets.ZIA_USERNAME }}
          ZIA_PASSWORD: ${{ secrets.ZIA_PASSWORD }}
          ZIA_API_KEY: ${{ secrets.ZIA_API_KEY }}
          ZIA_CLOUD: ${{ secrets.ZIA_CLOUD }}
          ZIA_SANDBOX_TOKEN: ${{ secrets.ZIA_SANDBOX_TOKEN }}
          ZPA_CLIENT_ID: ${{ secrets.ZPA_CLIENT_ID }}
          ZPA_CLIENT_SECRET: ${{ secrets.ZPA_CLIENT_SECRET }}
          ZPA_CUSTOMER_ID: ${{ secrets.ZPA_CUSTOMER_ID }}
          ZPA_CLOUD: ${{ secrets.ZPA_CLOUD }}
          TF_ACC: ${{ secrets.TF_ACC }}
          ZIA_ACC_TEST_FORCE_SWEEPERS: ${{ secrets.ZIA_ACC_TEST_FORCE_SWEEPERS }}
    needs:
      - zia-zsbeta-tests

  zia-zscalerone-test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        goVersion: ["1.21"]
        environment:
          - ZIA_ZS1
    environment: ${{ matrix.environment }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.goVersion }}

      - name: Set Go env
        run: |
          echo "GOPATH=$(go env GOPATH)" >> $GITHUB_ENV
          echo "$(go env GOPATH)/bin" >> $GITHUB_PATH

      - name: Setup Go Tools
        run: make tools

      - name: Download Go Dependencies
        run: |
          go mod tidy && go mod vendor

      - name: Setup Go Tools
        run: make tools

      - name: Check Formatting
        run: make fmtcheck

      - name: Vet Code
        run: make vet

      - name: Lint Code
        run: make lint

      - name: Check Build
        run: make build

      - name: Run tests with retry on Ubuntu
        uses: nick-fields/retry@v3
        with:
          max_attempts: 3
          timeout_minutes: 45 # Adjust as needed
          command: |
            make sweep
            make test:integration:zscalerone
            make sweep
        env:
          ZIA_USERNAME: ${{ secrets.ZIA_USERNAME }}
          ZIA_PASSWORD: ${{ secrets.ZIA_PASSWORD }}
          ZIA_API_KEY: ${{ secrets.ZIA_API_KEY }}
          ZIA_CLOUD: ${{ secrets.ZIA_CLOUD }}
          ZIA_SANDBOX_TOKEN: ${{ secrets.ZIA_SANDBOX_TOKEN }}
          ZPA_CLIENT_ID: ${{ secrets.ZPA_CLIENT_ID }}
          ZPA_CLIENT_SECRET: ${{ secrets.ZPA_CLIENT_SECRET }}
          ZPA_CUSTOMER_ID: ${{ secrets.ZPA_CUSTOMER_ID }}
          ZPA_CLOUD: ${{ secrets.ZPA_CLOUD }}
          TF_ACC: ${{ secrets.TF_ACC }}
          ZIA_ACC_TEST_FORCE_SWEEPERS: ${{ secrets.ZIA_ACC_TEST_FORCE_SWEEPERS }}
    needs:
      - zia-zsbeta-tests

  zia-zscalertwo-test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        goVersion: ["1.21"]
        environment:
          - ZIA_ZS2
    environment: ${{ matrix.environment }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.goVersion }}

      - name: Set Go env
        run: |
          echo "GOPATH=$(go env GOPATH)" >> $GITHUB_ENV
          echo "$(go env GOPATH)/bin" >> $GITHUB_PATH

      - name: Setup Go Tools
        run: make tools

      - name: Download Go Dependencies
        run: |
          go mod tidy && go mod vendor

      - name: Setup Go Tools
        run: make tools

      - name: Check Formatting
        run: make fmtcheck

      - name: Vet Code
        run: make vet

      - name: Lint Code
        run: make lint

      - name: Check Build
        run: make build

      - name: Run tests with retry on Ubuntu
        uses: nick-fields/retry@v3
        with:
          max_attempts: 3
          timeout_minutes: 45 # Adjust as needed
          command: |
            make sweep
            make test:integration:zscalertwo
            make sweep
        env:
          ZIA_USERNAME: ${{ secrets.ZIA_USERNAME }}
          ZIA_PASSWORD: ${{ secrets.ZIA_PASSWORD }}
          ZIA_API_KEY: ${{ secrets.ZIA_API_KEY }}
          ZIA_CLOUD: ${{ secrets.ZIA_CLOUD }}
          ZIA_SANDBOX_TOKEN: ${{ secrets.ZIA_SANDBOX_TOKEN }}
          ZPA_CLIENT_ID: ${{ secrets.ZPA_CLIENT_ID }}
          ZPA_CLIENT_SECRET: ${{ secrets.ZPA_CLIENT_SECRET }}
          ZPA_CUSTOMER_ID: ${{ secrets.ZPA_CUSTOMER_ID }}
          ZPA_CLOUD: ${{ secrets.ZPA_CLOUD }}
          TF_ACC: ${{ secrets.TF_ACC }}
          ZIA_ACC_TEST_FORCE_SWEEPERS: ${{ secrets.ZIA_ACC_TEST_FORCE_SWEEPERS }}
    needs:
      - zia-zsbeta-tests
